"""Conversations rewamp

Revision ID: a4980eb65016
Revises: 0625bc75ab77
Create Date: 2021-08-20 12:16:23.067185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4980eb65016'
down_revision = '0625bc75ab77'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('subject')
        batch_op.drop_column('draft')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
