"""Update SQLAlchemy 2

Revision ID: 1770409336
Revises: 0625bc75ab77
Create Date: 2026-02-06 21:22:16.464657

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1770409336"
down_revision = "0625bc75ab77"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.alter_column(
            "shared_id",
            existing_type=sa.NUMERIC(precision=16),
            type_=sa.Uuid(),
            existing_nullable=False,
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.alter_column("message", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.alter_column("message", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.alter_column(
            "shared_id",
            existing_type=sa.Uuid(),
            type_=sa.NUMERIC(precision=16),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
